[package]
name = "minimal_wasm_template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.wasm-bindgen]
version = "0.2"

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1